timings:
  peak:
    -
      days:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      timings:
        - ["07:00", "10:30"]
        - ["17:00", "20:00"]
    -
      days:
        - 6
        - 7
      timings:
        - ["09:00", "11:00"]
        - ["18:00", "22:00"]

default: off_peak
